<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="6" failures="0" skipped="0" tests="6" time="4.634" timestamp="2022-07-11T19:54:01.798292" hostname="Yigits-MacBook-Air-2.local"><testcase classname="" name="aws-dynamodb-encryption-python.examples.test.test_aws_kms_encrypted_examples" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/erinc/Documents/python-test-selection/python-rts-evaluation/aws-dynamodb-encryption-python/examples/test/test_aws_kms_encrypted_examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
aws-dynamodb-encryption-python/examples/test/test_aws_kms_encrypted_examples.py:15: in &lt;module&gt;
    from dynamodb_encryption_sdk_examples import (
E   ModuleNotFoundError: No module named 'dynamodb_encryption_sdk_examples'</error></testcase><testcase classname="" name="aws-dynamodb-encryption-python.examples.test.test_most_recent_provider_encrypted_examples" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/erinc/Documents/python-test-selection/python-rts-evaluation/aws-dynamodb-encryption-python/examples/test/test_most_recent_provider_encrypted_examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
aws-dynamodb-encryption-python/examples/test/test_most_recent_provider_encrypted_examples.py:18: in &lt;module&gt;
    from dynamodb_encryption_sdk_examples import most_recent_provider_encrypted_table
E   ModuleNotFoundError: No module named 'dynamodb_encryption_sdk_examples'</error></testcase><testcase classname="" name="aws-dynamodb-encryption-python.examples.test.test_wrapped_encrypted_examples" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/erinc/Documents/python-test-selection/python-rts-evaluation/aws-dynamodb-encryption-python/examples/test/test_wrapped_encrypted_examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
aws-dynamodb-encryption-python/examples/test/test_wrapped_encrypted_examples.py:15: in &lt;module&gt;
    from dynamodb_encryption_sdk_examples import wrapped_rsa_encrypted_table, wrapped_symmetric_encrypted_table
E   ModuleNotFoundError: No module named 'dynamodb_encryption_sdk_examples'</error></testcase><testcase classname="" name="aws-dynamodb-encryption-python.test.functional.encrypted.test_client" time="0.000"><error message="collection failure">aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:203: in _get_from_cache
    return _DELEGATED_KEY_CACHE[dk_class][algorithm][key_length]
E   KeyError: 2048

During handling of the above exception, another exception occurred:
aws-dynamodb-encryption-python/test/functional/encrypted/test_client.py:38: in pytest_generate_tests
    set_parametrized_cmp(metafunc)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:306: in set_parametrized_cmp
    metafunc.parametrize(name, _all_possible_cmps(algorithm_generator, require_attributes))
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/python.py:1272: in parametrize
    argnames, parametersets = ParameterSet._for_parametrize(
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:160: in _for_parametrize
    parameters = cls._parse_parametrize_parameters(argvalues, force_tuple)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in _parse_parametrize_parameters
    return [
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in &lt;listcomp&gt;
    return [
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:285: in _all_possible_cmps
    inner_cmp = builder_func(encryption_algorithm, encryption_key_length, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:213: in build_static_jce_cmp
    authentication_key = _get_from_cache(JceNameLocalDelegatedKey, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:205: in _get_from_cache
    key = dk_class.generate(algorithm, key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:215: in generate
    key, key_type, key_encoding = key_generator(key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:59: in _generate_rsa_key
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_length, backend=default_backend())
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py:132: in generate_private_key
    return ossl.generate_rsa_private_key(public_exponent, key_size)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py:515: in generate_rsa_private_key
    res = self._lib.RSA_generate_key_ex(
E   KeyboardInterrupt</error></testcase><testcase classname="" name="aws-dynamodb-encryption-python.test.functional.encrypted.test_item" time="0.000"><error message="collection failure">aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:203: in _get_from_cache
    return _DELEGATED_KEY_CACHE[dk_class][algorithm][key_length]
E   KeyError: 2048

During handling of the above exception, another exception occurred:
aws-dynamodb-encryption-python/test/functional/encrypted/test_item.py:41: in pytest_generate_tests
    set_parametrized_cmp(metafunc, require_attributes=False)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:306: in set_parametrized_cmp
    metafunc.parametrize(name, _all_possible_cmps(algorithm_generator, require_attributes))
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/python.py:1272: in parametrize
    argnames, parametersets = ParameterSet._for_parametrize(
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:160: in _for_parametrize
    parameters = cls._parse_parametrize_parameters(argvalues, force_tuple)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in _parse_parametrize_parameters
    return [
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in &lt;listcomp&gt;
    return [
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:285: in _all_possible_cmps
    inner_cmp = builder_func(encryption_algorithm, encryption_key_length, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:213: in build_static_jce_cmp
    authentication_key = _get_from_cache(JceNameLocalDelegatedKey, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:205: in _get_from_cache
    key = dk_class.generate(algorithm, key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:215: in generate
    key, key_type, key_encoding = key_generator(key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:59: in _generate_rsa_key
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_length, backend=default_backend())
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py:132: in generate_private_key
    return ossl.generate_rsa_private_key(public_exponent, key_size)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py:515: in generate_rsa_private_key
    res = self._lib.RSA_generate_key_ex(
E   KeyboardInterrupt</error></testcase><testcase classname="" name="aws-dynamodb-encryption-python.test.functional.encrypted.test_resource" time="0.000"><error message="collection failure">aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:203: in _get_from_cache
    return _DELEGATED_KEY_CACHE[dk_class][algorithm][key_length]
E   KeyError: 2048

During handling of the above exception, another exception occurred:
aws-dynamodb-encryption-python/test/functional/encrypted/test_resource.py:34: in pytest_generate_tests
    set_parametrized_cmp(metafunc)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:306: in set_parametrized_cmp
    metafunc.parametrize(name, _all_possible_cmps(algorithm_generator, require_attributes))
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/python.py:1272: in parametrize
    argnames, parametersets = ParameterSet._for_parametrize(
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:160: in _for_parametrize
    parameters = cls._parse_parametrize_parameters(argvalues, force_tuple)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in _parse_parametrize_parameters
    return [
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/_pytest/mark/structures.py:146: in &lt;listcomp&gt;
    return [
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:285: in _all_possible_cmps
    inner_cmp = builder_func(encryption_algorithm, encryption_key_length, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:213: in build_static_jce_cmp
    authentication_key = _get_from_cache(JceNameLocalDelegatedKey, signing_algorithm, signing_key_length)
aws-dynamodb-encryption-python/test/functional/functional_test_utils.py:205: in _get_from_cache
    key = dk_class.generate(algorithm, key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:215: in generate
    key, key_type, key_encoding = key_generator(key_length)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/dynamodb_encryption_sdk/delegated_keys/jce.py:59: in _generate_rsa_key
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_length, backend=default_backend())
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py:132: in generate_private_key
    return ossl.generate_rsa_private_key(public_exponent, key_size)
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py:521: in generate_rsa_private_key
    return _RSAPrivateKey(
../../../opt/anaconda3/envs/prot-pred-1/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/rsa.py:379: in __init__
    res = backend._lib.RSA_check_key(rsa_cdata)
E   KeyboardInterrupt</error></testcase></testsuite></testsuites>